### PR TITLE
Code style fixes

### LINKED ISSUE #138: Non-portable format strings
When compiling for systems where types such as int32_t are unequal to int (e.g., long int), then compilation fails. Please, use the defines from inttypes.h when defining format strings.

For example:
```
..\..\Components\safeclib\safeclib-core\tests\test_memcmp_s.c:193:35: error: format '%d' expects argument of type 'int', but argument 4 has type 'int32_t {aka long int}' [-Werror=format=]
         debug_printf("%s %u  Ind=%d  rc=%u \n", __FUNCTION__, __LINE__, ind,
                                  ~^
                                  %ld
```

If you want, I could also create a PR with the required changes. During configure one would need to check that inttypes.h is available and otherwise fallback to default definitions assuing that int32_t equals int, for example.

Alternatively, one could define variables as int instead of int32_t if this type is expected by the APIs anyways.

### PR DESCRIPTION
**Pull request by mschulz-at-hilscher**
This PR includes the following fixes:
- Removes whitespaces from end of lines.
- Converts indentation from tabs to spaces in *.c and *.h files.
- References unused variables to get rid of warnings.
- Uses portable format specifiers from inttypes.h.
- Uses variable types matching the memcmp_s APIs.
- Explicitly states which warnings to ignore during tests.

Fixes #138.

### CODE REVIEW

**Comment by rurban** [comment]
Looks good, I'll check tomorrow

**Comment by mschulz-at-hilscher** [comment]
i will send an update on monday. should be the references to unused variables before variable declarations.

**Comment by mschulz-at-hilscher** [comment]
@rurban can you retrigger the tests, please.

**Comment by mschulz-at-hilscher** [comment]
Is the "main" check broken or is there still something wrong in my changes?

**Comment by rurban** [comment]
I think FreeBSD had some recent unrelated changes

**Review by rurban — APPROVED** [review]

**Review by rurban — APPROVED** [review]

**Pull request merged**
